import type { Metadata } from "next";
import "@/styles/globals.css";
import Script from "next/script";
import AppClientLayout from "@/components/layouts/AppClientLayout";
import { THEME } from "@/packages/configs/app.config";
import { getThemeFontClassName } from "@/packages/utils/fonts";
import { themeInitScript } from "@/packages/utils/theme";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      data-scroll-behavior="smooth"
      className={`${getThemeFontClassName(THEME)} h-full antialiased`}
    >
      <head>
        {/* Runs before hydration so the correct .dark class is applied
            before first paint — prevents a flash of the wrong theme. */}
        <Script id="theme-init" strategy="beforeInteractive">
          {themeInitScript}
        </Script>
      </head>
      <body suppressHydrationWarning={true}>
        <AppClientLayout>{children}</AppClientLayout>
      </body>
    </html>
  );
}
